### ISSUE TITLE
privacy policy for page view tracker plugin for Confluence

### ISSUE THREAD

**Issue by dbylander** [chris-kent/Page-View-Tracker#1]
Atlassian's marketplace said that the privacy policy for this plugin was available from the vendor.  Please let me know if I've asked in the wrong venue.  
I basically want to know if the data from the plugin conforms to Confluence's permission scheme, that page  view data is restricted to people (wiki space administrators, say,) who have Confluence permission to view the page's data,  I need this assurance before I can go forward and start testing the plugin.
Thanks for your help,
Marty Bylander
University of Texas at Austin.

**Comment by chris-kent** [comment]
Hi Marty,

Yes the information gathered is only rendered on a page using a built in
Macro. Therefore this obeys the Page permissions. If a User does not have
permission to View the Page then they will not see the Page View
information. The MAcro will only show the current page data, no others, so
the information is secure.

Let me know if you need further information.

Cheers
Chris
