### ISSUE TITLE
page - view-tracker application

### ISSUE THREAD

**Issue by ektrontek** [chris-kent/Page-View-Tracker#3]
Dear Support Team, 
Is there sql which we can get how many views by pages by spaces in page - view tracker macro ? Thanks a lot.

**Comment by chris-kent** [comment]
Hi There,

You can use this query to get the total page views for specific Pages.
Unfortuanely there is no way of knowing which PageId is in which Space from
this table.

However you could JOIN the results from the Bandana table to another table
that might have Space/Page relationships. I don't know this and would need
to research and investigate myself.

But this query will give you the data from the Page View Tracker plugin.

select bandanavalue from public.Bandana where bandanacontext =
'net.kentcom.PageViewTracker.All.' + <pageid> AND bandanakey = 'TotalCount'

Hopw this helps

Chris

**Comment by ektrontek** [comment]
Dear Chris, 
Can we get view count by month/week in a page ? Thanks a lot.
Best Regards, Anderson Hsu

**Comment by chris-kent** [comment]
Hi Anderson,

I'm not sure what you exactly want, your 2 requests above are dissimilar?

The current plugin version does not track metrics which could be used for historical purposes.

However, the next release, which will be out within the next week, will start to track these metrics, so that daily/weekly/monthly historical view data will be available per page.

I hope this helps

Chris

**Comment by ektrontek** [comment]
Dear Chris, 
Thanks for your kindly assistance. I have also update the plugin to the latest version. Would it be possible to add sub sql command in the command ?
[https://photos.google.com/search/_tra_/photo/AF1QipOhPdcvT5DPrkuEP1rJEOFLRRSbdbUJs5dqfKpv](url)

For example , we can use select pageid from content to list all pageid information. If it can added for sub-sql in the command . I think it's useful.
Best Regards, Anderson Hsu

**Comment by chris-kent** [comment]
Hi Anderson,

I can't open the link, I get 400 error.

I'm not sure what you mean by a sub sql command? or what you mean by "we can use select pageid from content to list all pageid information"??

Can you please provide further information, context and maybe some examples or screenshots?

Thanks
Chris

**Comment by ektrontek** [comment]
Dear Chris, 
How about this link of https://photos.google.com/share/AF1QipPtTBWmLkhwCqR8IlaY10YCzvTv3Z27QKIsplNedpXJu7wZSPztwEycgJOT0--jnQ?key=TU52eTR3d212V2Qyc3czVEEyWUMtS2hPS0d0SVFB ?
Yes , I think we can get all pageid from content to list all pageid information . Is it ok ?
Best Regards, Anderson Hsu

**Comment by ektrontek** [comment]
Dear Chris,
How about this link of
https://photos.google.com/share/AF1QipPtTBWmLkhwCqR8IlaY10YCzvTv3Z27QKIsplNedpXJu7wZSPztwEycgJOT0--jnQ?key=TU52eTR3d212V2Qyc3czVEEyWUMtS2hPS0d0SVFB
 ?
Yes , I think we can get all pageid from content to list all pageid
information . Is it ok ?
Best Regards, Anderson Hsu

**Comment by chris-kent** [comment]
Hi Anderson,

Since you have upgraded to the latest version, you can use this query to get page history - I think this is what you are after...

select bandanavalue from public.Bandana where bandanacontext ='net.kentcom.PageViewTracker.Daily.' + <pageid>'

This will give you a set of key/value pairs, the bandanakey is a "date" key in the form YYYYMMDD and the bandanavalue is the total number of views for that page on each Date.

You should then be able to manipulate the data any way you like...

I Hope this helps

Chris

**Comment by chris-kent** [comment]
Hi Anderson,

I'm just checking in to see if the last query was any help to you?

Chris

**Comment by ektrontek** [comment]
Thanks for your kinds assistance. Regards Anderson Hsu

2017年12月12日 下午6:31，"chris-kent" <notifications@github.com>寫道：

**Comment by ektrontek** [comment]
Dear Chris,
I think I have try the collect sql command as shown as below, but where is
the date field in Bandana or where is date field in Page-View-Tracker ?
Thanks  a lot.
*SELECT TAB2.pageid, TAB1.title ,TAB3.spacename*
*FROM content TAB1,*
*(SELECT pageid FROM content*
*WHERE pageid IN (select cast(right(bandanacontext,8) as integer) as
contentcode from public.Bandana where bandanakey='TotalCount') and pageid
is not null) TAB2,spaces TAB3 *
*WHERE TAB2.pageid =  TAB1.contentid and TAB1.spaceid = TAB3.spaceid*

*Best Regards, Anderson Hsu*

**Comment by chris-kent** [comment]
Date is the bandanakey, see my comment from earlier, when you use the correct context (also see correction below)...

"This will give you a set of key/value pairs, the bandanakey is a "date" key in the form YYYYMMDD and the bandanavalue is the total number of views for that page on each Date."

I think there was a missing piece in the query above, it should read:
select bandanavalue from public.Bandana where bandanacontext ='net.kentcom.PageViewTracker.Daily.' + **'<pageId>'**;

There is no reason for you to use 'TotalCount', this gives no history (dates), it is the total views of the page since the plugin was first installed.

I see that you have been looking at the table to get the TotalCount key. How about you look at all the other keys and you should see the pattern quite easily. Hint, All the bandanacontext start with "net.kentcom.PageViewTracker"........

HTH
Chris

**Comment by ektrontek** [comment]
Dear Support Team,
Would it be possible to help us how to change  bandanakey field to normal
datetime field in posgresql database? I try this method as shown as below:
*select CONVERT(CHAR(4),LEFT(bandanakey,4)) & '/'&
SUBSTRING(bandanakey,4,2) & '/' & RIGHT(bandanakey,2) from public.Bandana
where bandanacontext like 'net.kentcom.PageViewTracker.Daily.%'*

or
*SELECT convert(datetime, bandanakey)*

But it still not work. Thanks for your kindly assistance.
Best Regards, Anderson Hsu

**Comment by chris-kent** [comment]
Hi,

Sorry I cannot change the schema of the bandana table, this is a built in Confluence tables for storing key/value pairs of type string. It is used for persistence by plugins.

Have you tried searching for solutions?, here is one: https://social.msdn.microsoft.com/Forums/sqlserver/en-US/3e5d6d62-449b-4084-9ae6-0dc82998c3bb/dataconversion-string-yyyymmdd-to-date?forum=transactsql

**Comment by ektrontek** [comment]
Thanks for your kindly assistance. I think it's ok now. Although I think
it's not a good way as shown as the attachment.
Best Regards, Anderson Hsu

**Comment by ektrontek** [comment]
Dear Chris,
I am sorry for bother you again. Would it be possible to know which account
view the page in the table of public.Bandana or other table ? Thanks for
your kindly assistance.
Best Regards, Anderson Hsu

**Comment by chris-kent** [comment]
Hi Anderson,
The best way to find which account is used to acess your db, is to look in the server.xml file in you Confluence installation directory to see which account Confluence uses to access the database.

Sorry I took so long reply.

Hope this helps.

Chris

**Comment by ektrontek** [comment]
Dear Chris,
Do you mean to enable log function in server.xml which I know the file and
it's path? I have a example file refer to the attachment.
Best Regards, Anderson Hsu

**Comment by chris-kent** [comment]
Hi Anderson,

You have lost me??? You asked about how to access your database to get public.bandana table. This has nothing to do with log files???,

Sorry I don't know what you are asking for.

**Comment by ektrontek** [comment]
Dear Chris,
Would it be possible to make sure what does it mean previous email content
which you mean as shown as below?

*The best way to find which account is used to acess your db, is to look in
the server.xml file in you Confluence installation directory to see which
account Confluence uses to access the database. *

Thanks for your kindly assistance.
Best Regards, Anderson Hsu

**Comment by chris-kent** [comment]
Hi Anderson,

You asked the question: "I am sorry for bother you again. Would it be possible to know which account
view the page in the table of public.Bandana or other table ? Thanks for
your kindly assistance."....

and my answer to this was to use the account for you Confluence database. As the public.bandana table is in the Confluence database that holds ALL of the Confluence data/tables/configuration.

I can't be any more specific than this and it answers your question exactly.

HTH
Chris

**Comment by ektrontek** [comment]
Dear Chris,
Sorry , I describe not clearly. I mean is there sql which can Query who
visits PAGE and how many times?
Best Regards, Anderson Hsu

**Comment by chris-kent** [comment]
select * from public.bandana where bandanacontext = "net.kentcom.PageViewTracker.Users." + <pageid>

the banadanakey is the username
the bandanavalue contains <total view count>-<last view time>

hth

**Comment by ektrontek** [comment]
Dear Chris,
Thanks for your kindly assistance. Would it be possible to confirm with you
why the result of page-view-tracker and confluence activity report is
different?
(We use sql command previous you give and use the result to compare with
the result of confluence activity report )
Best Regards, Anderson Hsu

**Comment by chris-kent** [comment]
Hi,
The reason the data is different because Confluence tracks statistics since
it was installed.
PageViewTracker only starts to track data from when the plugin was
installed. That's why the data, if you need to compare, will be different.
Cheers
Chris

**Comment by ektrontek** [comment]
Dear Chris,
Do you mean after install PageViewTracker  plugn, Confluence tracks
statistics report will be equal the result of pageviewtracker plugin? For
example , if we install pageviewtracker plugin at 2018/1/20, and then we
can check the result of pageviewtracker plugin with confluence tracks
statistics report after 2018/1/20 . Thanks  a lot.
Best Regards, Anderson Hsu

**Comment by ektrontek** [comment]
Dear Chris,
About the issue, my main purpose is to find a formal method to
do verification about my theory or my program code is right, so I ask more
and more question about view count question from different plugin support
or confluence support , such as user login count, page viewed count. Thanks
for your kindly assistance about my question.

My sql query is as listed as below: (Because I setup log function in
/opt/atlassian/confluence/conf/server.xml , refer to the article log
<https://confluence.atlassian.com/confkb/audit-confluence-using-the-tomcat-valve-component-223216846.html?_ga=2.61572591.2101070926.1518434108-1321040226.1507470095&_gac=1.119910522.1518089498.Cj0KCQiAh_DTBRCTARIsABlT9MbwBesiLYuzWxJqrBTIvp42jnMU67q9lbF0t1ky7zStBe_fcyOvYgUaAr0xEALw_wcB>
,
and then import log data to database to analysis the view count result )
select * from log0201 where ((d3 like '%viewpage.action%') and (d3 like
'%spaceKey=BB%')
I think it's right refer confluence support feedback as shown as ticket.png
attachment.

But when I try to find plugin support to find verification about my theory,
I found it's different with plugin support, such as Page-View-Tracker
plugin, Viewtrack plugin, Tracking Access for Confluence plugin.

Additional information: At the same time , I also ask confluence community
to find out more confluence activity report at the link of community
<https://community.atlassian.com/t5/Confluence-questions/view-count-question-in-confluence-activity-report/qaq-p/726683#U732514>

Best Regards, Anderson Hsu

**Comment by chris-kent** [comment]
Hi Anderson,

I am not sure what you are trying to do with log files etc, and this does
not seem to have anything to do with View-Tracker-Plugin. I'm sorry I
cannot answer this question.

Cheers

**Comment by ektrontek** [comment]
Dear Chris,
Do you mean after install PageViewTracker  plugn, Confluence tracks
statistics report will be equal the result of pageviewtracker plugin? For
example , if we install pageviewtracker plugin at 2018/1/20, and then we
can check the result of pageviewtracker plugin with confluence tracks
statistics report after 2018/1/20 . Thanks for your kindly assistance.
Best Regards, Anderson Hsu
