### ISSUE TITLE
i don.t have a item in the menu.

### ISSUE THREAD

**Issue by hangmana** [chris-kent/Page-View-Tracker#4]
Hello, there.
I installed a plugin. But i can't find this item "Page View Statistics" in the menu.
I checked my privilegues in Confluence. 
I am the administrator of Confluence, and the administrator of a Space.

![default](https://user-images.githubusercontent.com/35597729/35147962-93493694-fd21-11e7-920b-f78675f4086b.png)
![default](https://user-images.githubusercontent.com/35597729/35148270-940ebff8-fd22-11e7-81c7-62df6e31033c.png)

**Comment by chris-kent** [comment]
Hi there,
Yes I found the problem, You should now have access to the tool on all pages as an admin, please download version 2.6 and retry.
Cheers
