### ISSUE TITLE
Query User view information by Date

### ISSUE THREAD

**Issue by ektrontek** [chris-kent/Page-View-Tracker#5]
Dear Support Team, 
Would it be possible to query user view information by date / account ? We use sql command as listed as below:
select * from public.bandana where bandanacontext like 'net.kentcom.PageViewTracker.Users.%'  order by to_date(bandanavalue, 'Month DD, YYYY')
But it can not successful to change bandanavalue field to date format. Would it be possible to give me suggestion about it. Thanks a lot.
Addition information : We found it's not normal date format in bandanavalue field

**Comment by chris-kent** [comment]
Hi,

If you try this date format, it should work.

"d MMM yyyy, h:mm a"

*This is the JAVA format for Date I use, you may need to find the
**equivalent** SQL format.*

Cheers

**Comment by ektrontek** [comment]
Dear Chris,
I try the code as shown as the attachment. It can work ,but the result is
not right. I also try another way as listed as below:
select *,to_date(SUBSTRING(bandanavalue from 3), 'Month DD, YYYY') from
public.bandana where bandanacontext like
'net.kentcom.PageViewTracker.Users.%'
But because the format of content is not the same, I can not use the way ,
would it be possible to give me about the suggestion of the question ?
Thanks a lot.
Best Regards, Anderson Hsu

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
不含病毒。www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by chris-kent** [comment]
The SQL will depend on what db engine you have, SQL Server/Postgres/Oracle
will all be different...

I assume you are using postgres, converting the string to date should work
following this guide
https://www.postgresql.org/docs/9.4/static/functions-formatting.html

to_date(bandanavalue, 'DD MON YYYY, HH:MI AM')

I think this might work, you should experiment for yourself

Chris

**Comment by ektrontek** [comment]
Thanks for your kindly assistance. It's useful information.
Best Regards, Anderson Hsu

**Comment by ektrontek** [comment]
I use the method of query as listed as below:
select * from public.bandana where bandanacontext like
'net.kentcom.PageViewTracker.Users.%' order by
split_part(rtrim(ltrim(bandanavalue, '<string>'), '</string>'), '-',
2)::timestamp desc
