### ISSUE TITLE
Page View Tracker plugin

### ISSUE THREAD

**Issue by ektrontek** [chris-kent/Page-View-Tracker#8]
Dear Support Team, 
Because page view tracker plugin is free, is there any agreement or law which we can install the plugin in commercial place ?Or It's doesn't matter whether I can install the plugin in the commercial place or in home environment. Thanks a lot.

**Comment by chris-kent** [comment]
Hi,

There is no restriction on how you use free plugins, as long as you have a
valid Confluence instance, then you are free to use as you please.

Enjoy

Cheers
